### PR TITLE
Test suite updates

### PR DESCRIPTION
**Pull request by mrichar1**
- Switch to py3 as default (>=3.6) drop 2.6
- Replace chromedriver_installer and manual chrome install with chromedriver-binary
- Use chromedriver-path to update PATH (via bash)
- brew-cask is now builtin to homebrew

Following on from #192 to potentially get things moving...

This PR moves us past the current `chromedriver` errors on travis. Tests won't run locally as the config options for the various oauth providers are in an encrypted config.py.enc, which only travis (or @peterhudec) can decrypt.

However when the tests fail on travis, we see nothing in the logs because `py.test` is set to hide exceptions (`--tb=no`) - presumably to avoid config secrets showing up in the traceback.

This leaves things at a bit of an impasse as far as fixing tests is concerned!

### CODE REVIEW

**Comment by ergo** [comment]
Can we easily override config.py?

**Comment by mrichar1** [comment]
I'm hoping that we can get the account information shared with the other team members - though it's possible that the accounts in `config.py` aren't purely test accounts and it wouldn't be suitable for other people to have access to them.

If we can't get the info 'direct' - then there are 2 options - either set up entirely new accounts with all the oauth2 providers - or get travis (which can decrypt the file) to fire the contents back (securely) when running. (I'd much prefer to avoid the latter approach though - it's a bit legally and morally messy!)

**Comment by peterhudec** [comment]
I still have the original config, but as @mrichar1 said, its full of personal accounts 🤦‍♂️ I would suggest to create new accounts just for this purpose. [Facebook has a way to create test accounts](https://developers.facebook.com/docs/apps/test-users/), maybe other providers have something similar.

You can add providers to the tests gradually one by one, just comment out all the providers except the ones you wan't to start with in the [`INCLUDE_PROVIDERS`](https://github.com/authomatic/authomatic/blob/master/tests/functional_tests/config-template.py#L55) list.

**Comment by peterhudec** [comment]
By the way, the logs on Travis CI are turned off not because of security issues (all the secrets should be obfuscated in the Authomatic logs as far as I remember), but because Travis truncates the log if it's too long and for me it was more important to see the end of it to debug the failing logins.

**Comment by mrichar1** [comment]
OK, so that's the tests working again!

I've just added a single provider (`facebook`) -they were already limited to a single framework (`flask`).

Next steps:

* Merge this into `master` (please add comments/reviews - good to have a second set of eyes over it all before it goes 'live').
* Set up more test accounts for other 'major' providers (going to try `github` and `twitter` next as the most viable).
* Modify or replace `liveandletdie` as it's creaking a little - I think something smaller/neater can be implemented using `gevent.pywsgi` which will save on dependencies.
* Revisit PRs/Issues to see which ones can be merged.

(I'll provide some more info on slack about how the fb developer stuff, accounts etc are set up and make sure other devs get access as needed).

**Comment by mrichar1** [comment]
That's `github` added to the test suite - still waiting on various 'clearances' in setting up a twitter development app/account. (twitter is oauth 1.0a so will be useful to give us coverage of that code - will also look at `openid` at some point).

**Comment by mrichar1** [comment]
The latest now add `twitter` (`oauth1`) testing (lots of forced pushing to hide a lot of sausage-making).

At this stage we have enough of a test suite running that I'm keen to see how the outstanding PRs fare when these tests run against them, so I'm going to merge this PR and see what happens! 

Note - Some providers like twitter have rate-limiting on auth, so PR travis runs may need to be manually restarted if these kick in from too many parallel travis runs.

**Pull request merged**
