### PR TITLE
Prepare release 1.0.0

### PR DESCRIPTION
**Pull request by ericof**
Prepare release ~~0.2.0~~ 1.0.0 of **authomatic**

### CODE REVIEW

**Comment by mrichar1** [comment]
Thanks for kicking this off again -I got the tests working but then never managed to get the final release done!

A couple of things...

Firstly the last travis run seems to have failed due to a `google-chrome` install issue, which I think is unrelated to the code, so it probably just needs a kick to run again.

Secondly (and more importantly) currently there's no automated mechanism in place for pypi releases via travis - and I believe only @peterhudec has pypi access. At the very lest he would have to add encrypted pypi credentials to `.travis.yml`, or ideally add the other github collaborators as project managers, or change the pypi account's email address to `authomaticproject@gmail.com` so it doesn't sit with just one person.

**Comment by jensens** [comment]
> and I believe only @peterhudec has pypi access.

No, we're in too.
Screenshot at 2019-11-25 10-13-53

**Comment by jensens** [comment]
So, here a before-release checklist from what I know by now (just edit this comment and add what is missing)

- [ ] fix travis (google-chrome install issue)
- [ ] fix pypi account's email address to authomaticproject@gmail.com
- [ ] overhaul README
- [ ] overhaul https://authomatic.github.io/authomatic/ (contact, providers, donate button (?), ....)
- [ ] check ``setup.py`` classifiers and metadata. 
- [ ] make a test release and check if all is in place
- [ ] make a manual release to PyPI

Nice to have:
- [ ] automatic release via Travis (or switch to Github Actions)
- [ ] use towncrier for changelog

**Comment by mrichar1** [comment]
I'm happy to get pypi updated and automatic releases via travis in place (doing this for a couple of other projects so have the process in my head).

Also happy to look at the google-chrome problem (I'm hopeful it's transient and will disappear on the next push).

**Comment by ericof** [comment]
@mrichar1 Right now the issue is not with Google Chrome anymore but with a functional test with Github authentication failing, but any help here is more than welcome

**Comment by mrichar1** [comment]
It looks like github is asking for device verification/2FA on the sign-in attempt from travis, by sending a one-time code via email. 

Unfortunately there's no easy way to get this into the test run I can think of, and automating 2FA would be fairly tricky.

We've had this with other providers and had to drop them from testing (e.g. google/gmail). Then the only options are to try to keep one of each 'type' (oauth1/2/openid) going, or run the test suite manually with an active browser session to interact with 2FA/verification etc.

**Comment by mrichar1** [comment]
I've just pushed a new config secrets file with github testing disabled - this should hopefully let us see if anything else is breaking (and we can revisit what suites to test at a later date).

**Comment by ericof** [comment]
@mrichar1 Perfect! Now it passes!

**Comment by mrichar1** [comment]
I've saved the `pypi` token as a 'secret' environment variable on the travis server called `$PYPI_PASSWORD` which should be used by travis during deployment.

It's currently configured to make a release for every tag pushed to the `master` branch - this can be tweaked a bit if we want a different 'schedule' - e.g. we can change `tags: true` to `branch: prepare-0.2.0` if we want to test things before merging to master.

Either way we should use one of the pre/dev release tag formats to test this build process: https://www.python.org/dev/peps/pep-0440/#pre-releases

**Comment by mrichar1** [comment]
OK - it looks like the automated pypi deployments are working - if you look at https://pypi.org/project/Authomatic/#history you can see an alpha pre-release I just pushed.

So the steps for generating an automated release are:

1. Edit `setup.py` and bump the version number (following PEP440).
2. Tag the release. The tag name is irrelevant, but it makes sense for it to mirror the version number.
3. Push to `master` branch (all other branches are ignored, tagged or otherwise).

Feel free to delete the `0.2.0a1` package in pypi if we want to keep things tidy (though as a pre-release pip etc shouldn't pick it up for install unless explicitly asked for).

**Comment by jensens** [comment]
I fixed docs simplified deployment and added autodeploy, turned into lean release and more.
Seems to work now
@ericof please test https://pypi.org/project/Authomatic/0.2.0a2/ if you can

**Comment by mrichar1** [comment]
I've added `pylint` and `pycodestyle` to the `tox` config, just testing for errors at this stage, and have tweaked the codebase to remove those reported (all aesthetic changes really). It's ignoring `six.py` at the moment because there are a lot of errors reported there that require 'real' code fixes, and with python 2 going away it seemed potentially not a useful task to focus on.

If you run `pylint` without `--errors-onoly` there are a lot of 'real' issues in the code: nothing scary, but messy things like code blocks after return statements, unused variables, inconsistent return behaviour etc. Once we have a release done I'll see about tidying some of these (and we can look at the Issue/PR backlog).

**Comment by mrichar1** [comment]
Many apologies - that wasn't @jensens - that was me accidentally telling travis to delete this branch at the end of the run (which used his token to do so).

Despite that, after a couple more pushes the whole build process seems to be working - pushing test pypi packages and creating docs at `test-ghpages` branch.

But annoyingly it looks like since the branch was deleted and recreated the PR can no longer be reopened :-(

However, given how many hacky commits went into me getting this working, it might not be a bad thing to 'start again' and hide some of the sausage-making. I'll see about making a new branch, cherry-picking/editing this branch onto it, and then open a new PR to replace this one.

**Comment by ericof** [comment]
@mrichar1 👍 Let's recreate and do it cleanly

**Comment by jensens** [comment]
I removed the `prepare-0.2.0` branch, it's done its duty.

**Pull request closed without merging**
