### PR TITLE
#89 fix problem of user not writting their location as 'city, country'

### PR DESCRIPTION
**Pull request by leojpod**
Hi @peterhudec, 

thanks for this library it works like a charm! 

But as I am part of the comma-less location users, I had to do something. 

Let me know if that "fix" fits your repo's spirite or if you would like to me change some things

### CODE REVIEW

**Comment by peterhudec** [comment]
@leojpod thanks for the PR, this will be fixed by all affected providers in **0.1.0** very soon.

**Comment by leojpod** [comment]
ok great !

**Comment by mrichar1** [comment]
@peterhudec can you confirm if this issue was fixed in 0.1.0, or if this PR is still needed? Thanks!

**Comment by peterhudec** [comment]
I'm afraid it's not fixed.

**Comment by leojpod** [comment]
I've attempted to quickly resolve the conflict (but I must say that it's been a while since I last had a look at that code...)

**Comment by leojpod** [comment]
hmm I've no idea. That was probably PyStorm being over zealous on the import ...

**Pull request merged**
