### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by jensens**
This is a major cleanup which does the following:

- run [autopep8](https://pypi.python.org/pypi/autopep8), which does not find everything, but is a good start.
- run [docformatter](https://pypi.python.org/pypi/docformatter) - it is a good start for a unified docstring appearance.
- I did a manual cleanup. I tried to go the 80-column way at most places. The most code now passes flake8 (as my sublime text editor enforces, I did not run it separately). At some points the style is a bit opinionated - or just the style I know from other projects, such as Plone. I am open for discussion or later changes.  While doing so I edited at very few places logic, like changing a complex trinary condition into a classic multiline ``if: else:` or using or removing unused local variables - so, nothing immersive.
- Python UTF8 headers are added. As a good kid we should have those to tell editors and interpreter what we expect.

### CODE REVIEW

**Comment by mrichar1** [comment]
Hope you don't mind me adding more commits to this in the same spirit (syntax and style changes only).

Also, in case it's useful, I just discovered the `?w=1` option on github change urls - see e.g: https://github.com/authomatic/authomatic/pull/174/commits/99b658cf769a76f322027f5bc6076e84dd7482da?w=1

**Comment by jensens** [comment]
Perfect, just add what's needed!

**Comment by jensens** [comment]
I think this branch is ready for merge @mrichar1 - what do you think?

**Comment by mrichar1** [comment]
I believe so - I've done as much as I think I can without starting to change code paths etc. If you're happy with my extra commits then I'm happy for a merge.

**Comment by jensens** [comment]
done!

**Pull request merged**
