### PR TITLE
Docs: Replace gendered language with gender agnostic pronouns

### PR DESCRIPTION
**Pull request by AetherUnbound**
This is a small docs (and comments) only change which changes the gendered "his/her" to the gender agnostic "their". This helps make the documentation more inclusive of gender minorities :slightly_smiling_face:

### CODE REVIEW

**Comment by mrichar1** [comment]
Thanks for submitting this PR. I don't see any issue with accepting this PR - though I do also see a few `' his ' ` in the code which could also do with changing, if you're hppy to find and change those too? Thanks!

**Comment by AetherUnbound** [comment]
Oh I missed those, yea I can change them too!

**Comment by AetherUnbound** [comment]
The only instance I didn't update was "Many thanks to Peter Hudec for all his hard work for creating and maintaining **authomatic**!", because I assume that one's accurate :slightly_smiling_face:

**Review by mrichar1 — APPROVED** [review]
:+1:

**Pull request merged**
