### PR TITLE
Github: run additional request to get email(s)

### PR DESCRIPTION
**Pull request by muravjov**
Hi! I noted, that email cannot be received for Github provider. This patch fixes it.

### CODE REVIEW

**Comment by muravjov** [comment]
The second commit fixes issue with required User-Agent header, see https://developer.github.com/v3/#user-agent-required

**Comment by muravjov** [comment]
You may reproduce the error with non-existing User-Agent header if you do not use GAE, GAE sets User-Agent itself to "Google-remote_api/1.0"

**Comment by kkinder** [comment]
Helpful. It's been several months now since this has been submitted. Anyone have ideas on implementing it?

FWIW, I was able to just monkey-patch this code, but that's far from ideal.

**Comment by mrichar1** [comment]
Hi - in case you don't currently have time for this (or are no longer using authomatic) would you consider ticking the `Allow edits from maintainers.` button on this PR to give us permission to write to your branch and merge it in? Thanks!

**Comment by mrichar1** [comment]
After several years of inactivity, authomatic is now under community management, and we have just released a new stable version (1.0.0).

We are now reviewing all issues and PRs and hoping to begin work to solve as many of these as possible.

We are keen to find out which issues still apply, and which PRs are still required/are likely to merge cleanly into the current code. We are aiming to review them all, but any help with prioritisation would be very useful!

If you are still interested in having this issue/PR resolved, or are able to help us work on it, please reply to this message. That way we know which issues are most important to the community.

**Comment by mrichar1** [comment]
Now in #212

**Pull request closed without merging**
